Automatically clean before making the rpm

diff --git a/dafrito-yum-repo b/dafrito-yum-repo
--- a/dafrito-yum-repo
+++ b/dafrito-yum-repo
@@ -3,6 +3,7 @@ PATH=/bin:/usr/bin
 
 RPMDIR=$HOME/rpmbuild
 REPODIR=/tmp/dafrito/repo.$$
+CLEAN=clean
 
 die() {
 	echo $* 1>&2
@@ -31,7 +32,7 @@ sync_package() {
 	shift
 	local path=`echo $1 | sed -e "s%^~%$HOME%"`
 	pushd $path || die "Failed to change directory to $path"
-	make rpm || die "Build failed for $name"
+	make $CLEAN rpm || die "Build failed for $name"
 	cp -p -v -t $REPODIR `rpm --specfile ./$name.spec -q | get_rpm_name` || die "Failed to copy packages"
 	popd
 }
